spring.application.name=backend_gympass
server.port=8087

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/db_reto?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root