spring.application.name=backend_gympass

# Conexion a la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/db_reto
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA — none para no tocar la BD, show-sql para ver las consultas en consola
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT — secret en Base64, expiration en milisegundos (86400000 = 24 horas)
jwt.secret=dWthRYPU96VXrPS5UK5hut8Ho/8iJNMocRzUgmQUWdI=
jwt.expiration=86400000
